name: "Bug report"
description: "Report a problem to help us improve"
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug concisely.
      placeholder: Clear, concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps, inputs, and expected vs actual.
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: Tag, commit SHA, or branch.
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs or images.

