name: "Feature request"
description: "Suggest an idea for this project"
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: What user/job-to-be-done are we addressing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: High-level outline of the solution and alternatives.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Definition of done / success metrics.

