from __future__ import annotations

import os

VERIFIER_CIRCUIT_COOLDOWN_S = int(os.getenv("VERIFIER_CIRCUIT_COOLDOWN_S", "60"))
VERIFIER_CIRCUIT_FAILS = int(os.getenv("VERIFIER_CIRCUIT_FAILS", "5"))
VERIFIER_CIRCUIT_WINDOW_S = int(os.getenv("VERIFIER_CIRCUIT_WINDOW_S", "60"))
VERIFIER_DAILY_TOKEN_BUDGET = int(os.getenv("VERIFIER_DAILY_TOKEN_BUDGET", "100000"))
VERIFIER_MAX_TOKENS_PER_REQUEST = int(
    os.getenv("VERIFIER_MAX_TOKENS_PER_REQUEST", "1000")
)
VERIFIER_TIMEOUT_MS = int(os.getenv("VERIFIER_TIMEOUT_MS", "1000"))

