meta:
  name: base
  version: 2
  tags: [default]

settings:
  ingress:
    sampling_pct: 1.0
  egress:
    # IMPORTANT: keep base neutral so pack order works (tests rely on this)
    redact_enabled: false

rules:
  deny:
    # --- violence / wrongdoing facilitation ---
    - id: deny.violence.bomb
      reason: "Violent wrongdoing facilitation (explosives)"
      pattern: "\\b(make|build|construct|assemble|create)\\b[\\s\\S]{0,80}\\b(bomb|ied|explosive|detonator|grenade)\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.violence.poison
      reason: "Violent wrongdoing facilitation (poisoning)"
      pattern: "\\b(poison|toxicant|ricin|cyanide|arsenic|fentanyl)\\b|\\b(how to|most effective way|best way)\\b[\\s\\S]{0,80}\\b(poison|kill|harm)\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.violence.weapon
      reason: "Violent wrongdoing facilitation (weapons)"
      pattern: "\\b(make|build|construct|assemble)\\b[\\s\\S]{0,80}\\b(weapon|silencer|suppressor|ghost gun|firearm)\\b"
      flags: ["i"]
      action: "block_input_only"

    # keep secrets deny (existing behavior)
    - id: deny.secrets
      reason: "Secret leakage (keys/passwords)"
      pattern: "(?i)\\b(api[_-]?key|password|secret[_-]?key|token)\\b"
      action: "block_input_only"

  allow: []
  redact: []
  verifiers: []
