meta:
  name: base
  version: 3
  tags: [default]

settings:
  ingress:
    sampling_pct: 1.0
  egress:
    # IMPORTANT: keep base neutral so pack order works (tests rely on this)
    redact_enabled: false

rules:
  deny:
    # --- violence / wrongdoing facilitation ---
    - id: deny.violence.bomb
      reason: "Violent wrongdoing facilitation (explosives)"
      pattern: "\\b(make|build|construct|assemble|create)\\b[\\s\\S]{0,80}\\b(bomb|ied|explosive|detonator|grenade)\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.violence.poison
      reason: "Violent wrongdoing facilitation (poisoning)"
      pattern: "\\b(poison|toxicant|ricin|cyanide|arsenic|fentanyl)\\b|\\b(how to|detail how to|step by step|instructions|most effective way|best way)\\b[\\s\\S]{0,80}\\b(poison|kill|harm)\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.violence.weapon
      reason: "Violent wrongdoing facilitation (weapons)"
      pattern: "\\b(make|build|construct|assemble)\\b[\\s\\S]{0,80}\\b(weapon|silencer|suppressor|ghost gun|firearm)\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.secrets.pem_private_key
      reason: "Secret leakage (private key material)"
      pattern: "-----BEGIN[\\s\\S]{0,40}PRIVATE KEY-----"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.secrets.github_token
      reason: "Secret leakage (GitHub token)"
      pattern: "\\b(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}\\b|\\bgithub_pat_[A-Za-z0-9_]{20,}\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.secrets.jwt
      reason: "Secret leakage (JWT token)"
      pattern: "\\beyJ[A-Za-z0-9_\\-]{5,}\\.[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: deny.secrets.aws_access_key_id
      reason: "Secret leakage (AWS access key id)"
      pattern: "\\b(AKIA|ASIA)[0-9A-Z]{16}\\b"
      flags: ["i"]
      action: "block_input_only"

    - id: safety.self_harm.ideation
      reason: "Self-harm ideation or encouragement"
      reason_hint: "self_harm_support"
      pattern: "(?i)\\b(i (want|plan) to (hurt|harm|kill) myself|i don['’]t want to live|end my life|commit suicide|self[- ]?harm|kill myself|hurt myself|cut myself)"
      action: "block_input_only"

    - id: toxicity.revenge.embarrass
      reason: "Requests to harass, embarrass, or seek revenge"
      reason_hint: "harassment_refusal"
      pattern: "(?i)\\b(help me|how do i|plan to) (embarrass|humiliate|dox|doxx|ruin (his|her|their) reputation|get revenge on)"
      action: "block_input_only"

    - id: safety.attachment.love
      reason: "Attachment or romantic dependency on the model"
      reason_hint: "attachment_boundary"
      pattern: "(?i)\\b(i (love|am in love with) you (chatgpt|claude|gemini|assistant)|be my (girlfriend|boyfriend|partner)|don['’]t leave me)"
      action: "block_input_only"

  allow: []
  redact: []
  verifiers: []
