# ruff: noqa: E501
from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(prefix="/admin/ui", tags=["admin-ui"])

_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Guardrail Admin — Active Policy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Simple self-contained styles; no external deps -->
  <style>
    :root { --bg:#0b0e14; --card:#121724; --text:#e6e6e6; --muted:#9aa4b2; --accent:#53b1fd; --ok:#34d399; --warn:#f59e0b; --bad:#ef4444; }
    html,body { margin:0; padding:0; background:var(--bg); color:var(--text);
            font:14px/1.4 ui-sans-serif, system-ui, -apple-system, Segoe UI,
            Roboto, Helvetica, Arial, "Apple Color Emoji","Segoe UI Emoji"; }
    header { padding:18px 20px; border-bottom:1px solid #1e2635; display:flex; align-items:center; gap:10px; }
    h1 { font-size:18px; margin:0; }
    .container { max-width:1100px; margin:24px auto; padding:0 20px; display:grid; grid-template-columns: 1fr 1fr; gap:16px; }
    .card { background:var(--card); border:1px solid #1e2635; border-radius:16px; padding:16px; box-shadow:0 4px 16px rgba(0,0,0,.25); }
    .card h2 { margin:0 0 10px; font-size:16px; }
    .kv { display:grid; grid-template-columns: 220px 1fr; gap:8px 12px; }
    .kv div { padding:6px 8px; border-radius:8px; background:#0e1420; }
    .tag { display:inline-block; padding:2px 8px; border-radius:999px; font-size:12px; background:#0e1420; border:1px solid #253248; color:var(--muted); }
    .grid { display:grid; gap:8px; }
    .muted { color:var(--muted); }
    code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
    pre { margin:0; overflow:auto; background:#0d1320; border:1px solid #1e2635; border-radius:12px; padding:12px; }
    .ok { color: var(--ok); }
    .warn { color: var(--warn); }
    .bad { color: var(--bad); }
    .footer { margin: 8px 20px 24px; color: var(--muted); font-size: 12px; }
    .pill { padding:4px 10px; border-radius:999px; border:1px solid #2a364c; background:#0d1320; color:#b6c2d0; }
    .row { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }
    @media (max-width: 900px) { .container { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <header>
    <div class="pill">Guardrail Admin</div>
    <h1>Active Policy</h1>
    <div class="row" style="margin-left:auto">
      <span class="muted">Read-only · v1</span>
    </div>
  </header>

  <div class="container">
    <section class="card" id="policyCard">
      <h2>Policy Overview</h2>
      <div class="kv" id="policyKv">
        <div>Policy Version</div><div id="policyVersion"><span class="muted">loading…</span></div>
        <div>Clarify HTTP Status</div><div id="clarifyStatus"><span class="muted">loading…</span></div>
      </div>
    </section>

    <section class="card">
      <h2>Env Toggles</h2>
      <div class="grid" id="envList"><span class="muted">loading…</span></div>
    </section>

    <section class="card" style="grid-column: 1 / -1;">
      <h2>Decision Map</h2>
      <pre id="decisionMap"><span class="muted">loading…</span></pre>
    </section>

    <section class="card" style="grid-column: 1 / -1;">
      <h2>Raw</h2>
      <pre id="raw"><span class="muted">loading…</span></pre>
    </section>
  </div>

  <div class="footer">
    TODO: add auth gating (OIDC/session) · generated by Hybrid-04
  </div>

  <script>
    async function fetchActive() {
      const r = await fetch('/admin/policies/active', { headers: { 'Accept': 'application/json' } });
      if (!r.ok) throw new Error('Failed to load active policy');
      return await r.json();
    }

    function kvRow(k, v) {
      const divK = document.createElement('div'); divK.textContent = k;
      const divV = document.createElement('div'); divV.textContent = v;
      return [divK, divV];
    }

    function render(data) {
      const policyVersion = document.getElementById('policyVersion');
      const clarifyStatus = document.getElementById('clarifyStatus');
      const envList = document.getElementById('envList');
      const decisionMap = document.getElementById('decisionMap');
      const raw = document.getElementById('raw');

      policyVersion.textContent = String(data.policy_version ?? 'unknown');
      const cs = data?.env_toggles?.CLARIFY_HTTP_STATUS ?? '422';
      clarifyStatus.textContent = String(cs);

      // Env toggles
      envList.innerHTML = '';
      const env = data.env_toggles || {};
      Object.keys(env).sort().forEach(k => {
        const row = document.createElement('div');
        row.className = 'row';
        const key = document.createElement('span'); key.className='tag'; key.textContent = k;
        const val = document.createElement('span'); val.textContent = String(env[k]);
        row.appendChild(key); row.appendChild(val);
        envList.appendChild(row);
      });

      // Decision map pretty
      decisionMap.textContent = JSON.stringify(data.decision_map ?? {}, null, 2);
      raw.textContent = JSON.stringify(data, null, 2);
    }

    fetchActive().then(render).catch(err => {
      const raw = document.getElementById('raw');
      raw.textContent = String(err);
    });
  </script>
</body>
</html>"""


@router.get("", response_class=HTMLResponse)
def admin_ui_root() -> HTMLResponse:
    return HTMLResponse(_HTML)
